#*****************************************************************************************
# Vivado (TM) v2021.2 (64-bit)
#
# final_project.tcl: Tcl script for re-creating project 'final_project'
#
# Generated by Vivado on Sat May 07 16:09:08 -0400 2022
# IP Build 3369179 on Thu Oct 21 08:25:16 MDT 2021
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (final_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "C:/Users/david/Desktop/final_project/final_project.srcs/sources_1/new/datapath.v"
#    "C:/Users/david/Desktop/final_project/final_project.srcs/sim_1/new/testbench.v"
#    "C:/Users/david/Desktop/final_project/final_project.srcs/utils_1/imports/synth_1/datapath.dcp"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

set_property SEVERITY {Warning} [get_drc_checks NSTD-1]
set_property SEVERITY {Warning} [get_drc_checks UCIO-1]
